FROM node:18-alpine

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY  . .
RUN npm run build

# Define environment variables
ENV NEXT_PUBLIC_REDIS_PASSWORD=${NEXT_PUBLIC_REDIS_PASSWORD}
ENV NEXT_PUBLIC_REDIS_HOST=${NEXT_PUBLIC_REDIS_HOST}
ENV DATABASE_URL=${DATABASE_URL}
ENV MONGODB_URI=${MONGODB_URI}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}

CMD [ "npm", "run", "start" ]
