name: NextJS Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
      env:
        NEXT_PUBLIC_REDIS_PASSWORD: ${{ secrets.NEXT_PUBLIC_REDIS_PASSWORD }}
        NEXT_PUBLIC_REDIS_HOST: ${{ secrets.NEXT_PUBLIC_REDIS_HOST }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
